name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy: 
      matrix: 
        redis-version: ">= 5"
        ruby-version: ['2.5', '2.6', '2.7', '3.0', '3.1']
      include:
        - redis-version: "< 5"
          ruby-version: "2.5"
    services:
      redis:
        image: redis
    env:
      REDIS_URL: redis://redis
      REDIS_VERSION: "${{ matrix.redis-version }}"
    steps:
      - uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with: 
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake
